# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
forward_step <- function(pi, A, emission_probs, P, loglik, k, n) {
    invisible(.Call(`_ensembleFHMM_forward_step`, pi, A, emission_probs, P, loglik, k, n))
}

#' @export
backward_sampling <- function(x, P, possible_values, k, n) {
    invisible(.Call(`_ensembleFHMM_backward_sampling`, x, P, possible_values, k, n))
}

#' @export
backward_step <- function(P, Q, k, n) {
    invisible(.Call(`_ensembleFHMM_backward_step`, P, Q, k, n))
}

#' @export
forward_backward_mod <- function(pi, A, emission_probs, k, n) {
    .Call(`_ensembleFHMM_forward_backward_mod`, pi, A, emission_probs, k, n)
}

#' @export
backward_step_mod <- function(P, Q, k, n) {
    .Call(`_ensembleFHMM_backward_step_mod`, P, Q, k, n)
}

#' @export
forward_backward_fast <- function(pi, A, B, y, k, n, marginal_distr) {
    .Call(`_ensembleFHMM_forward_backward_fast`, pi, A, B, y, k, n, marginal_distr)
}

#' @export
crossover <- function(x, y, t) {
    invisible(.Call(`_ensembleFHMM_crossover`, x, y, t))
}

#' @export
crossover2 <- function(x, y, t, n) {
    invisible(.Call(`_ensembleFHMM_crossover2`, x, y, t, n))
}

#' @export
crossover_one_element <- function(x, y, t) {
    invisible(.Call(`_ensembleFHMM_crossover_one_element`, x, y, t))
}

#' @export
crossover_mat <- function(X, Y, t, which_rows) {
    invisible(.Call(`_ensembleFHMM_crossover_mat`, X, Y, t, which_rows))
}

#' @export
decimal_to_binary_mapping <- function(K) {
    .Call(`_ensembleFHMM_decimal_to_binary_mapping`, K)
}

#' @export
hamming_ball <- function(index, radius, mapping) {
    .Call(`_ensembleFHMM_hamming_ball`, index, radius, mapping)
}

#' @export
construct_all_hamming_balls <- function(radius, mapping) {
    .Call(`_ensembleFHMM_construct_all_hamming_balls`, radius, mapping)
}

#' @export
construct_restricted_space <- function(x_t, which_rows_fixed, mapping) {
    .Call(`_ensembleFHMM_construct_restricted_space`, x_t, which_rows_fixed, mapping)
}

#' @export
construct_all_restricted_space <- function(k_restricted, which_rows_fixed, mapping) {
    .Call(`_ensembleFHMM_construct_all_restricted_space`, k_restricted, which_rows_fixed, mapping)
}

